# Site settings

baseurl = "http://s645360620.online.de/"
theme = "ridingbytes"
title = "Kloster Helfta"
languageCode = "de-de"
copyright = "Copyright (c) 2016, Kloster Helfta"


[permalinks]
    blog = "/:year/:month/:day/:slug/"


[taxonomies]
    tag = "tags"
    category = "categories"


[params]

    # To provide some metadata for search engines feel free to add a few
    # information about you and your website.
    name = "Zisterzienserinnen Kloster St. Marien zu Helfta"
    description = "Zisterzienserinnen Kloster St. Marien zu Helfta in der Lutherstadt Eisleben"
    keywords = "Kloster,Zisterzienser,Helfta,Gertrud,Mechthild,Mechtild,Abtei,Zisterzienserinnen,Orden,monastisch,Luther,Eisleben,Heilige"
    dateformat = "Mon,2 Jan, 2006"
    disqusShortname = "klosterhelfta"


    # navigation
    [params.navigation]
        title = "Navigation"
        description = ""

        [[params.navigation.list]]
            title = "Zu Hause"
            href = "/"
            submenu = [
                ["/#services", "Zisterzienserinnenkloster"],
                ["/#gertrudstift", "Gertrudstift"],
                ["/#kinderhaus", "Montessori-Kinderhaus St. Marien"],
                ["/#mechthildstift", "Caritas-Pflegezentrum St. Mechthild"],
            ]
        [[params.navigation.list]]
            title = "Zu Gast"
            href = "/zugast"
            submenu = [
                ["/zugast/#fuehrungen", "Führungen"],
                ["/zugast/#uebernachten", "Übernachtungen"],
                ["/zugast/#essen", "Essen & Trinken"],
                ["/zugast/#kurse", "Kurse & Seminare"],
 		["/zugast/#exerzitien", "Exerzitien"],
		["/zugast/#gespraeche", "Gespräche"],
                ["/zugast/#Klosterladen", "Klosterladen"],
                ["/zugast/#feiern", "Feiern"],
 		["/zugast/#ausfluege", "Ausflugsziele"],
            ]
        [[params.navigation.list]]
            title = "Programm"
            href = "Programm-2016.pdf"
        [[params.navigation.list]]
            title = "Aktuelles"
            href = "/aktuelles"
        [[params.navigation.list]]
            title = "Hintergründe"
            href = "/hintergruende"
        [[params.navigation.list]]
            title = "Kontakt"
            href = "/kontakt"


    # main site sections
    [params.sections]

        # home section /
        [params.sections.home]
            title = "Zu Hause"
            href = "/"

	# zu Gast section /zugast
	[params.sections.zugast]
	    title = "Zu Gast"
	    href = "/zugast"
	    img = "gaestehaus.jpg"

        # blog section /aktuelles
        [params.sections.blog]
            title = "Aktuelles"
            subtitle = ""
            href = "/aktuelles"

        # services section /angebote
        [params.sections.services]
            title = "Angebote"
            subtitle = ""
            href = "/angebote"

        # about section /about
        [params.sections.about]
            title = "Hintergründe"
            subtitle = "Das Kloster und seine Geschichte"
            href = "/hintergruende"

        # portfolio section /programm
        [params.sections.portfolio]
            title = "Programm"
            subtitle = "Kurse, Seminare, Exerzitien, Vorträge"
            href = "Programm-2016.pdf"

        # contact section /kontakt
        [params.sections.contact]
            title = "Kontakt"
            subtitle = "Sagen Sie doch mal 'Hallo'"
            href = "/kontakt"

        # 404 section /404
        [params.sections.fourohfour]
            title = "404"
            subtitle = "Sorry, the Page your requested could not be found"
            description = "Page Not Found"


    # slider
    [params.slider]

        # slide 1
        [[params.slider.slides]]
            img = "slide-2.jpg"
            alt = "Kloster Helfta"
            [[params.slider.slides.layers]]
                img = "kloster_weiss.png"
                alt = "Kloster Helfta"
                start = "750"
                y = "210"
            [[params.slider.slides.layers]]
                description = "ZISTERZIENSERINNENKLOSTER ST. MARIEN"
                start = "800"
                y = "400"
                cls = "font-accident-one-normal fontcolor-invert"
            [[params.slider.slides.layers]]
                link = "Mehr erfahren"
                href = "#services"
                start = "950"
                y = "480"
                cls = "page-scroll btn btn-lg btn-wh-str"

        # slide 2
        [[params.slider.slides]]
           img = "slide-1.jpg"
            alt = "Gertrudfenster - Moderne trifft Mystik"
            [[params.slider.slides.layers]]
                title = "MODERNE TRIFFT MYSTIK"
                start = "800"
                y = "210"
                cls = "font-accident-one-bold-shadow fontcolor-invert"
            [[params.slider.slides.layers]]
                description = "IN ARCHITEKTUR UND GEBET"
                start = "850"
                y = "285"
                cls = "font-accident-one-normal-shadow fontcolor-invert"
            [[params.slider.slides.layers]]
                link = "Mehr erfahren"
                href = "/hintergruende"
                start = "950"
               y = "365"
                cls = "page-scroll btn btn-lg btn-wh-str"

        # slide 3
        [[params.slider.slides]]
            img = "slide-4.jpg"
            alt = ""
            [[params.slider.slides.layers]]
                title = "OASE DER STILLE"
                start = "800"
                y = "210"
                cls = "font-accident-one-bold-shadow fontcolor-invert"
            [[params.slider.slides.layers]]
               description = "EINKEHR • SAMMLUNG • GOTTESBEGEGNUNG"
                start = "850"
                y = "285"
                cls = "font-accident-one-normal-shadow fontcolor-invert"
            [[params.slider.slides.layers]]
                link = "Mehr erfahren"
                href = "#services"
                start = "950"
                y = "365"
                cls = "page-scroll btn btn-lg btn-wh-str"

        # slide 4
       # [[params.slider.slides]]
        #    img = "slide-5.jpg"
         #   alt = ""
          #  [[params.slider.slides.layers]]
           #     title = "ORT INTENSIVER GOTTESBEGEGNUNG"
            #    start = "800"
             #   y = "210"
              #  cls = "font-accident-one-bold fontcolor-invert"
          #  [[params.slider.slides.layers]]
           #     description = "KLOSTERKIRCHE • GERTRUDKAPELLE • LABYRINTH"
            #    start = "850"
             #   y = "285"
              #  cls = "font-accident-one-light fontcolor-invert"
           # [[params.slider.slides.layers]]
            #    link = "Mehr erfahren"
             #   href = "#services"
              #  start = "950"
               # y = "365"
                #cls = "page-scroll btn btn-lg btn-wh-str"

        # slide 5
#        [[params.slider.slides]]
 #           img = "slide-6.jpg"
  #          alt = ""
   #         [[params.slider.slides.layers]]
    #            title = "MIT LEIDENSCHAFT"
     #           start = "800"
      #          y = "210"
       #         cls = "font-accident-one-bold fontcolor-invert"
        #    [[params.slider.slides.layers]]
         #       description = "OFFEN • KREATIV • HERZLICH"
          #      start = "850"
           #     y = "285"
            #    cls = "font-accident-one-light fontcolor-invert"
            #[[params.slider.slides.layers]]
             #   link = "Mehr erfahren"
              #  href = "#services"
               # start = "950"
                #y = "365"
                #cls = "page-scroll btn btn-lg btn-wh-str"

    # pricing
  #  [params.pricing]
   #     title = "Service Package Offers"
    #    description = "Time-Boxed Service Packages"

     #   [[params.pricing.list]]
      #      title = "16h"
       #     subtitle = "Introductory"
        #    discount = "10% Discount"
         #   description = "* One Time Bookable *"
          #  subdescription = "Ideal for new Customers"
           # cls = "pricing plain"
            #details = [
             #   ["16 Hours Fixed Time Package"],
              #  ["Development"],
               # ["Consulting"],
           # ]

      #  [[params.pricing.list]]
       #     title = "20h"
        #    subtitle = "Small"
         #   discount = "5% Discount"
          #  description = "Developer Package"
           # subdescription = "Ideal for Small Projects"
            #cls = "pricing plain"
            #details = [
             #   ["20 Hours Fixed Time Package"],
              #  ["Develpment"],
               # ["UI / UX DESIGN"],
           # ]

    #    [[params.pricing.list]]
     #       title = "50h"
      #      subtitle = "Business"
       #     discount = "5% Discount"
        #    description = "Developer/Admin Package"
         #   subdescription = "Ideal for Intermediate Projects"
          #  cls = "pricing proposal"
           # details = [
            #    ["50h Fixed Time Package"],
             #   ["Development"],
              #  ["UI / UX DESIGN"],
               # ["Administration"],
            #]

     #   [[params.pricing.list]]
      #      title = "100h"
       #     subtitle = "Professional"
        #    discount = "10% Discount"
         #   description = "Complete Package"
          #  subdescription = "Ideal for Large/Ongoing Projects"
           # cls = "pricing plain"
            #details = [
             #   ["100h Fixed Time Package"],
              #  ["Development"],
               # ["Consulting"],
                #["UI / UX DESIGN"],
               # ["Administration"],
            #]

    # services
    [params.services]
        title = "Angebote"
        description = "Da-Sein vor Gott für die Menschen"
        [[params.services.list]]
            title = "Kloster"
            description = "Zisterzienserinnen in Helfta"
            cls = "icon-box"
            href = "/kloster"
            details = [
                ["gelebte Hingabe"],
                ["liebevolles Miteinander"],
                ["kreative Offenheit"]
            ]
        [[params.services.list]]
            title = "Gästehaus"
            description = "Herzlich Willkommen!"
            cls = "icon-layers"
            href = "/zugast"
            details = [
                ["Gruppenreisen"],
                ["Einzelgäste"],
                ["Tagesausflügler"]
            ]
        [[params.services.list]]
            title = "Gertrudstift"
            description = "Wohnung mieten in Helfta"
            cls = "icon-eye"
            href = "/services/#gertrudstift"
            details = [
                ["einzigartige Nachbarschaft"],
                ["besonderes Ambiente"],
                ["nahe Einkaufsmöglichkeiten"]
            ]
        [[params.services.list]]
            title = "Mechthildsaal"
            description = "Feste feiern in Helfta"
            cls = "icon-server"
            href = "/services/#mechthildsaal"
            details = [
                ["Hochzeiten"],
                ["Konzerte"],
                ["Geburtstage"]
            ]


    # gertrudstift
    [params.gertrudstift]
        title = "Wohnen in Helfta"
        description = "Zur Miete leben in unmittelbarer Nähe zum Kloster"
        [[params.team.members]]
            img = "ramon.jpg"
            name = "Ramon Bartl"
            position = "Owner & Coder"
            social = [
                ["fa-twitter", "https://twitter.com/ramonbartl"],
                ["fa-linkedin", "https://www.linkedin.com/in/ramonski"],
                ["fa-github", "https://github.com/ramonski"],
                ["fa-facebook", "https://www.facebook.com/ramonbartl"]
            ]
        [[params.team.members]]
            img = "lucky.jpg"
            name = "Lucky Luke"
            position = "Leadership Coach and Mentor"
            social = [
                ["fa-twitter", "https://twitter.com/ridingbytes"],
               # ["fa-linkedin", "https://www.linkedin.com/company/riding-bytes"],
                ["fa-github", "https://github.com/ridingbytes"],
                ["fa-facebook", "https://www.facebook.com/ridingbytes"]
            ]


    # partners
    [params.partners]
        title = "Partners"
        description = "More than just one Company – A worldwide Network of strong Partners"

        [[params.partners.list]]
            name = "Bika Lab Systems"
            logo = "bika.jpg"
            href = "http://www.bikalabs.com"
            description = "Bika Labs provides up-market Open Source Laboratory Information Management Systems."

        [[params.partners.list]]
            name = "KGM GmbH"
            logo = "kgm.png"
            href = "http://www.k-g-m.com"
            description = "KGM is an independend Marketing Agency, which offers brilliant Concepts and Services around Brand Creation, and Recognition."

        [[params.partners.list]]
            name = "nexiles GmbH"
            logo = "nexiles.png"
            href = "http://www.nexiles.com"
            description = "Nexiles offers Services around Product Development and Information Management."


    # customers
    [params.customers]
        title = "Customers"
        description = "Sustainable IT Solutions for all kinds of Businesses"

        [[params.customers.list]]
            name = "Alpenleder"
            logo = "alpenleder.png"
            href = "http://www.alpenleder.com"
            description = "We provide a holistic business solution for Alpenleder with a complete integration of their Website, Sales and E-Commerce Requirements in Odoo ERP."

        [[params.customers.list]]
            name = "2degrees Mobile Limited"
            logo = "2degrees.png"
            href = "http://www.2degreesmobile.co.nz"
            description = "We support 2degrees Mobile in New Zealand to interface their Data Management Server with their existing IT Infrastructure."

        [[params.customers.list]]
            name = "Gletscher Cola"
            logo = "gletschercola.png"
            href = "http://www.gletschercola.de"
            description = "We support Gletscher Cola with Consulting and Development Services."


    # systems
    [params.systems]
        [[params.systems.links]]
            title = "Plone"
            url = "https://plone.org"
            img = "plone.png"
        [[params.systems.links]]
            title = "ExtJS"
            url = "https://sencha.com"
            img = "extjs.png"
        [[params.systems.links]]
            title = "Odoo"
            url = "https://odoo.com"
            img = "odoo.png"
        [[params.systems.links]]
            title = "GitHub"
            url = "https://github.com"
            img = "github.png"
        [[params.systems.links]]
            title = "Python"
            url = "https://python.com"
            img = "python.png"
        [[params.systems.links]]
            title = "CoffeeScript"
            url = "http://coffescript.org"
            img = "coffeescript.png"


    # about the company
    [params.about]
        title = "Kloster Helfta"
        [[params.about.infos]]
            text = "Das Zisterzienserinnenkloster St. Marien zu Helfta ist ein Ort des Gebetes, der Begegnung und des Friedens."
        [[params.about.infos]]
            text = "Als jüngstes Zisterzienserinnenkloster Deutschlands befindet sich Helfta in vielerlei Hinsicht noch im Aufbau und bietet Raum für kreative Köpfe, die ein modernes monastisches Leben führen möchten."


    # contact information
    [params.contact]
        title = "Kontakt"
        name = "Kloster St. Marien zu Helfta"
        phone = "+49 (0) 3475 711-500"
        email = "schwestern@kloster-helfta.de"
        address = "Kloster St. Marien zu Helfta, Lindenstraße 36, 06295 Lutherstadt Eisleben"
        web = "http://kloster-helfta.de"

        [params.contact.form]
            title = "Kontakt aufnehmen"
            subtitle  = "Schreiben Sie den Schwestern, was Ihnen auf dem Herzen liegt!"
            buttonText = "Nachricht senden"
            to = "schwestern@kloster-helfta.de"

        # 'warning' defines error messages for invalid inputs
        [params.contact.form.name]
            text = "Ihr Name *"
            warning = "Bitte geben Sie Ihren Namen ein."
        [params.contact.form.email]
            text = "Ihre Email-Adresse *"
            warning = "Bitte geben Sie Ihre Email-Adresse ein."
        [params.contact.form.phone]
            text = "Ihre Telefonnummer *"
            warning = "Bitte geben Sie Ihre Telefonnummer ein."
        [params.contact.form.message]
            text = "Ihre Nachricht *"
            warning = "Bitte schreiben Sie Ihre Nachricht."


    # social media links
    [params.follow]
        title = "Follow us"
        [[params.follow.list]]
            title = "Facebook"
            href = "https://www.facebook.com/ridingbytes"
            cls = "fa fa-facebook"
        [[params.follow.list]]
            title = "GitHub"
            href = "https://github.com/ridingbytes"
            cls = "fa fa-github"
       # [[params.follow.list]]
        #    title = "LinkedIn"
         #   href = "https://www.linkedin.com/company/riding-bytes"
          #  cls = "fa fa-linkedin"
        [[params.follow.list]]
            title = "Twitter"
            href = "https://twitter.com/ridingbytes"
            cls = "fa fa-twitter"


    # flickr feed
    [params.flickr]
        title = "Impressions"

    # twitter feed
    [params.twitter]
        title = "Latest News"
        login = "ridingbytes"
        widgetId = "646968545675476992"
        number = 5

    # facebook feed
    [params.facebook]
        title = ""

    # google analytics
    [params.googleanalytics]
        uac = "UA-71580219-1"

    # copyright
    [params.copyright]
        year = "2016"
        text = "All rights reserved"

        # additional copyright links
        #[[params.copyright.links]]
            #title = "Impressum"
            #url = ""
        [[params.copyright.links]]
            title = "Impressum"
            url = "/legal"
